# Generated by Django 5.2.1 on 2026-04-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название лекарства')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity_in_stock', models.PositiveIntegerField(verbose_name='Количество на складе')),
                ('expiration_date', models.DateField(verbose_name='Срок годности')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('requires_prescription', models.BooleanField(default=False, verbose_name='По рецепту')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
                'ordering': ['-expiration_date'],
            },
        ),
    ]
